from django.urls import path
from . import views


urlpatterns = [
    path("auth/admin/login", views.admin_login),
    path("auth/superadmin/login", views.superadmin_login),
    path("auth/admin/change-credentials", views.admin_change_credentials),
    path("superadmin/dashboard", views.superadmin_dashboard),
    path("superadmin/admins", views.superadmin_admins),
    path("superadmin/admins/<uuid:admin_id>", views.superadmin_admin_detail),
    path("superadmin/codes/reset", views.superadmin_reset_codes),
    path("superadmin/logs", views.superadmin_logs),
    path("articles", views.articles),
    path("articles/<uuid:record_id>", views.article_detail),
    path("events", views.events),
    path("events/<uuid:record_id>", views.event_detail),
    path("events/<uuid:event_id>/register", views.event_register),
    path("events/<uuid:event_id>/registrations", views.event_registrations),
    path("events/<uuid:event_id>/is-registered", views.event_is_registered),
    path("events/<uuid:event_id>/registrations/<uuid:registration_id>/attendance", views.event_attendance),
    path("events/<uuid:event_id>/attendance-summary", views.attendance_summary),
    path("members", views.members),
    path("members/<uuid:member_id>", views.member_detail),
    path("members/<uuid:member_id>/status", views.member_status),
    path("members/<uuid:member_id>/activities", views.member_activities),
    path("contributions", views.contributions),
    path("contributions/initiate", views.initiate_contribution),
    path("contributions/<uuid:contribution_id>/confirm", views.confirm_contribution),
    path("contributions/payment-links", views.payment_links),
    path("contributions/payment-links/<uuid:link_id>", views.payment_link_detail),
    path("partners", views.partners),
    path("partners/<uuid:record_id>", views.partner_detail),
    path("testimonials", views.testimonials),
    path("testimonials/<uuid:record_id>", views.testimonial_detail),
    path("gallery/albums", views.gallery_albums),
    path("gallery/albums/<uuid:record_id>", views.gallery_album_detail),
    path("gallery/photos", views.gallery_photos),
    path("gallery/photos/<uuid:record_id>", views.gallery_photo_detail),
    path("team-members", views.team_members),
    path("team-members/<uuid:record_id>", views.team_member_detail),
    path("newsletter/subscribe", views.newsletter_subscribe),
    path("newsletter/subscribers", views.newsletter_subscribers),
    path("stats", views.stats),
    path("settings", views.site_settings),
]
