name: CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev, main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "📦 Checkout du code"
        uses: actions/checkout@v4

      - name: "⚙️ Configuration de Node.js (v24)"
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      # --- FRONTEND ---
      - name: "🎨 Installation des dépendances (Frontend)"
        working-directory: ./frontend
        run: npm ci

      - name: "🏗️ Build du Frontend"
        working-directory: ./frontend
        run: npm run build

      # --- BACKEND (Python / Django) ---
      - name: "⚙️ Configuration de Python"
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'backend/requirements.txt'

      - name: "🔌 Installation des dépendances (Backend Django)"
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: "🚀 Vérification Django (Backend)"
        run: |
          python backend/manage.py check
